# Generated by Django 3.2.4 on 2021-07-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210622_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type_of_event',
            field=models.CharField(blank=True, choices=[('c', 'Культура'), ('e', 'Образование'), ('s', 'Спорт'), ('o', 'Остальные')], default='o', max_length=1),
        ),
    ]
