# Generated by Django 3.2.4 on 2021-07-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_type_of_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.CharField(max_length=20, verbose_name='date event'),
        ),
    ]
