# Generated by Django 3.2.4 on 2021-07-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type_of_event',
            field=models.CharField(choices=[('o', 'Остальные'), ('s', 'Спорт'), ('c', 'Культура'), ('e', 'Образование')], default='o', max_length=1),
        ),
    ]
